### ISSUE TITLE
Drop Symb. phase?

### ISSUE THREAD

**Issue by Amuri44** [JuliaSparse/KLU.jl#6]
How can I reserve the symb. phase?

**Comment by Wimmerer** [comment]
It should be `klu!(factor, A2)`

Let me know if that works

**Comment by Wimmerer** [comment]
```julia
K = klu(A)
x = K \ b
klu!(K, nzval2)
x2 = K \ copy(b)
x2  == solve(K, b)
...
...
```

Note that this modifies `b`.

If you must use `solve` it operates in the same way.

`solve` and `\` do not re-do the symbolic phase _unless_ necessary. Also be sure to check your matrices with `rcond` or `rgrowth`.

**Comment by Amuri44** [comment]
Thank you very much!
