### ISSUE TITLE
Implicit promotion from F32 to F64

### ISSUE THREAD

**Issue by mzy2240** [JuliaSparse/KLU.jl#9]
```julia
factor = klu(A);
```
When `A` is a sparse matrix of `Float32` type, feeding into `klu` will result in a `Float64` factorized matrix. Is it possible to stick to `Float32` for the whole symbolic and numerical factorization process?

**Comment by Wimmerer** [comment]
No, unfortunately `Float64` and `ComplexF64` are the only supported numeric types. See Section 5 of https://fossies.org/linux/SuiteSparse/KLU/Doc/KLU_UserGuide.pdf. I'll have a port of KLU to Julia native out as soon as I find time to polish it. Which will support any numeric type. 

I'll leave this open for now to remind me to ping here when I release the port.

**Comment by mzy2240** [comment]
Did not aware that KLU only supports `double`. Sorry for the unreasonable request and definitely looking forward to the Julia native implementation!
